var team = {
	title: "Meet our team",
	size: "full",
	members: [
		{
			name: "Scott Slinker",
			title: "Founder & CEO",
			accomplishment: "Not getting BBQ on my white shirt",
			music: "Phantogram",
			activity: "Friday night poker tournament",
			portrait: "a.SS.347wx341h.Paradata-2-1.ScottSlinker.png",
			linkedin: "https://www.linkedin.com/in/scottslinker",
		},
		{
			name: "Dr. Pat Selinger",
			title: "CTO",
			accomplishment: "The people I mentor and the teams I work with",
			music: "Any country music, from Johnny Cash to Taylor Swift",
			activity: "Hanging out with friends and family, wine tasting",
			portrait: "a.PS.347wx341h.PatSelinger.NEW.8.2015.Paradata-7-1.png",
			linkedin: "",
		},
		{
			name: "Carmine Napolitano",
			title: "CFO",
			accomplishment: "My natural ability to sleep and eat, unfortunately neither are monetizable so I’m a CFO instead",
			music: "The Smiths",
			activity: "Playing, watching, or refereeing soccer",
			portrait: "a.CN.347wx341hParadataNEW.8.2015.CarmineCFO-5-1-web.png",
			linkedin: "",
		},
		{
			name: "Andy Hunt",
			title: "VP of Sales",
			accomplishment: "That I will go down as the voice of this generation ... Oh wait, that's Kanye!",
			music: "Dave Matthews Band (Live)",
			activity: "College football. Go Blue!",
			portrait: "a.AH.Paradata.AndyHunt.347wx341h.NEW.png",
			linkedin: "https://www.linkedin.com/in/connectwithandyhunt",
		},
		{
			name: "Linda Duyonavich",
			title: "VP of Programs",
			accomplishment: "My kids",
			music: "The Grateful Dead",
			activity: "Gardening and spending time with friends",
			portrait: "a.LD.nored.LindaDuyanovichParadata-8-1-web.png",
			linkedin: "",
		},
		{
			name: "Joel Nave",
			title: "VP of Products",
			accomplishment: "My kids",
			music: "U2 (vintage)",
			activity: "Sports with kids",
			portrait: "a.JN.347wx341hParadata.NEW.8.2015.-13-1-web.JOELNAVE.png",
			linkedin: "",
		},
		{
			name: "Dr. Karen Brannon",
			title: "Data Acquisition Lead",
			accomplishment: "My family",
			music: "So many bands, so little time",
			activity: "Hiking",
			portrait: "a.female.ParadataPhoto.347wx341h.Paradata-9-1-web.png",
			linkedin: "",
		},
		{
			name: "Jim Brady",
			title: "Chief Scientist",
			accomplishment: "My family",
			music: "Boston Pops",
			activity: "Target rifle shooting",
			portrait: "a.JBJimBrady.face.347x341.wb.png",
			linkedin: "",
		},
		{
			name: "Dr. Bruce Lindsay",
			title: "Chief Data Scientist",
			accomplishment: "",
			music: "",
			activity: "",
			portrait: "a.BL.347x341pixels.BruceLindsay.wb.png",
			linkedin: "",
		},
		{
			name: "Chris Owen",
			title: "VP of Engineering",
			accomplishment: "My kids",
			music: "Coldplay",
			activity: "The beach",
			portrait: "a.CO.ChrisOwen.347x341.wb.png",
			linkedin: "",
		},
		{
			name: "Kanda Kaliappan",
			title: "Director of Quality Assistance",
			accomplishment: "My family, teams and products that I helped to build",
			music: "Any soft rock music",
			activity: "Playing with kids and spending time with friends",
			portrait: "a.KP.347wx341hKanda.wb.png",
			linkedin: "",
		},
		{
			name: "Chris Page",
			title: "Database Architect",
			accomplishment: "I am part of a great team that is dedicated to working together to deliver quality time and again",
			music: "Pat Metheny Group",
			activity: "Tennis 'til I drop",
			portrait: "a.CP.ChrisPage.347x341h.wb.png",
			linkedin: "",
		},
	],
};